FileVersion = 1
Projects = {FantyEngine = {Path = "."}, Sandbox = {Path = "Sandbox"}, bon = {Path = "vendor/bon"}, ImGui = {Path = "vendor/imgui-beef"}, FantyEditor = {Path = "FantyEditor"}, FantyRuntime = {Path = "FantyRuntime"}, GLFW = {Path = "vendor/glfw-beef"}}

[Workspace]
StartupProject = "FantyEditor"
