FileVersion = 1
Projects = {Sandbox = {Path = "Sandbox"}, FantyEditor = {Path = "FantyEditor"}, FantyRuntime = {Path = "FantyRuntime"}, GLFW = {Path = "FantyEngine/vendor/glfw-beef"}, FantyEngine = {Path = "FantyEngine"}, ImGui = {Path = "FantyEngine/vendor/imgui-beef"}, bon = {Path = "FantyEngine/vendor/bon"}}

[Workspace]
StartupProject = "FantyEditor"

[Configs.Test.Win32]
ConfigSelections = {Sandbox = {Config = "Debug"}}

[Configs.Test.Win64]
ConfigSelections = {Sandbox = {Config = "Debug"}}
