FileVersion = 1
Dependencies = {corlib = "*", Sandbox = "*", bon = "*", ImGui = "*", FantyEngine = "*", GLFW = "*"}

[Project]
Name = "FantyEditor"
StartupObject = "FantyEditor.Program"

[Platform.Windows]
IconFile = "$(ProjectDir)/assets/desktop/icon_32.ico"
Company = "Boxsubmus"
Product = "Fanty Editor"
Copyright = "2023"

[Configs.Release.Win64]
PostBuildCmds = ["CopyFilesIfNewer(\"$(ProjectDir)/assets\", \"$(BuildDir)\")"]

[Configs.Debug.Win64]
PostBuildCmds = ["CopyFilesIfNewer(\"$(ProjectDir)/assets\", \"$(BuildDir)\")"]
