FileVersion = 1
Dependencies = {corlib = "*", Sandbox = "*", bon = "*", ImGui = "*", FantyEngine = "*", GLFW = "*"}

[Project]
Name = "FantyEditor"
StartupObject = "FantyEditor.Program"

[Platform.Windows]
IconFile = "$(ProjectDir)/assets/desktop/icon_1024.ico"

[Configs.Release.Win64]
PostBuildCmds = ["CopyFilesIfNewer(\"$(ProjectDir)/assets\", \"$(BuildDir)\")"]
